//// <auto-generated> This file has been auto generated. </auto-generated>
//namespace Microsoft.VisualStudio.TestPlatform
//{
//    internal class TestSDKAutoGeneratedCodeAttribute : Attribute
//    {
//    }
//}